pipelines:
  default:
    - step:
        name: Sync GitHub Mirror
        image: alpine/git:latest
        clone:
          enabled: false
        script:
          - git clone --bare git@bitbucket.org:cbytedigital/laravel-teams-logger.git
          - cd laravel-teams-logger.git
          - git push --mirror git@github.com:cbytedigital/laravel-teams-logger.git
